// <auto-generated />
using Emeint.Core.BE.Media.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Emeint.Core.BE.Media.Migrations
{
    [DbContext(typeof(MediaContext))]
    [Migration("20180221121741_ModifyingTable")]
    partial class ModifyingTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.BE.Media.Domain.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("BinaryData")
                        .IsRequired();

                    b.Property<string>("ClientReferenceNumber")
                        .IsRequired();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<string>("Comment");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime>("CreationDate");

                    b.Property<int?>("Height");

                    b.Property<string>("ImagePath");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<int?>("OriginalBinaryDataLength");

                    b.Property<string>("Tag");

                    b.Property<string>("TenantCode");

                    b.Property<int?>("Width");

                    b.HasKey("Id");

                    b.HasIndex("ClientReferenceNumber")
                        .IsUnique();

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Images","Media");
                });
#pragma warning restore 612, 618
        }
    }
}
